# fly.toml app configuration file generated for aidhan-study on 2023-08-20T20:19:29+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "aidhan-study"
primary_region = "syd"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
